baseURL = "https://conner.codes"
#languageCode = "en-us"
canonifyURLs = true
theme = "cfzero-theme"
sectionPagesMenu = ""
title = "Conner Codes, and Blogs, and codes some more"

post = "/:year/:month/:title/"

[params]
    siteName = "Conner Codes"
    siteOwner = "CFZero Labs"

[taxonomies]

[menu]
    [[menu.main]]
        identifier = "home"
        pre = ""
        name = "Home"
        url  = "/"
        weight = 1
    [[menu.main]]
        identifier = "about"
        pre = ""
        name = "About"
        url  = "/about/"
        weight = 2
    [[menu.main]]
        identifier = "blog"
        pre = ""
        name = "Blog"
        url  = "/post/"
        weight = 3